with-expecter: true
packages:
  gopkg.in/telebot.v3:
    config:
      dir: internal/bot
      outpkg: bot
    interfaces:
      Context:
        config:
          mockname: mockContext
          filename: mock_context_test.go
